name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: show_python_version
        run: |
          python -V
          python3 -V

      - name: show_pip_version
        run: |
          pip -V
          pip3 -V

      - name: fix_python3_venv
        run: sudo apt-get update && sudo apt-get install python3-venv

      - uses: jdxcode/rtx-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mkdir -p ~/.local/share/rtx/plugins
      - run: ln -s $PWD ~/.local/share/rtx/plugins/python
      - run: rtx i pipenv@latest
      - run: rtx x pipenv@latest -- pipenv --version
